services:
  - type: web
    env: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120
    envVars:
      - key: FLASK_DEBUG
        value: "0"
